// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.11.8
//   protoc               v7.34.1
// source: proto/stock.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "stock";

export interface StockRequest {
  productId: number;
  quantity: number;
}

export interface StockResponse {
  available: boolean;
  message: string;
}

export const STOCK_PACKAGE_NAME = "stock";

export interface StockServiceClient {
  checkAndReserve(request: StockRequest): Observable<StockResponse>;
}

export interface StockServiceController {
  checkAndReserve(request: StockRequest): Promise<StockResponse> | Observable<StockResponse> | StockResponse;
}

export function StockServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkAndReserve"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("StockService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("StockService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const STOCK_SERVICE_NAME = "StockService";
